library/urls.py
from django.urls import path

from . import views

app_name = 'library'
urlpatterns = [
    path('', views.home_page, name='home'),
    path('authors', views.AuthorListView.as_view(), name='authors'),
    path('languages', views.LanguageListView.as_view(), name='languages'),
    path('languages/<int:language_id>', views.books_by_language, name='language_books'),
    path('authors/<int:author_id>', views.books_by_author, name='authors_works'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('add_author', views.add_author, name='add_author'),
    path('add_book', views.add_book, name='add_book'),
    path('upload_authors', views.upload_authors, name='upload_authors'),
    path('upload_books', views.upload_books, name='upload_books')
]

library_catalog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls'))
]

library/models.py
from django.db import models


class User(models.Model):
    email = models.EmailField(unique=True)


class Language(models.Model):
    language = models.TextField(max_length=30, unique=True)

    def __str__(self):
        return self.language


class Country(models.Model):
    country = models.TextField(max_length=30, unique=True)

    def __str__(self):
        return self.country


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    birth_date = models.DateField()
    death_date = models.DateField(null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def count_books(self):
        return Book.objects.filter(author=self).count()


class Book(models.Model):
    title = models.CharField(max_length=100)
    # TODO: null=True should be removed eventually
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    # TODO: add support for an arbitrary number of secondary authors
    publication_date = models.DateField()
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.title} ({self.publication_date.year})"


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_read = models.DateField()
    rating = models.IntegerField()
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)

library/views.py
import csv, io
from datetime import datetime

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Author, Book, Country, Language


YMD_FORMAT = "%Y-%m-%d"


class AuthorListView(generic.ListView):
    template_name = 'library/authors.html'
    context_object_name = 'author_list'

    def get_queryset(self):
        return Author.objects.order_by('last_name')


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'library/book_detail.html'


def home_page(request):
    return render(request, 'library/home.html')


def books_by_author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    books = Book.objects.filter(author=author).order_by('publication_date')
    context = {
        'author': author,
        'books': books
    }
    return render(request, 'library/author_books.html', context)


class LanguageListView(generic.ListView):
    template_name = 'library/languages.html'
    context_object_name = 'language_list'

    def get_queryset(self):
        return Language.objects.order_by('language')


def books_by_language(request, language_id):
    language = get_object_or_404(Language, pk=language_id)
    books = Book.objects.filter(language=language).order_by('author', 'publication_date')
    context = {
        'language': language,
        'books': books
    }
    return render(request, 'library/language_books.html', context)


def add_author(request):
    if request.method == 'POST':
        new_author = Author()
        new_author.first_name = request.POST['first_name']
        new_author.last_name = request.POST['last_name']
        new_author.birth_date = request.POST['birth_date']
        new_author.death_date = request.POST['death_date'] or None
        new_author.country = Country.objects.get(pk=request.POST['country'])
        new_author.save()
        return HttpResponseRedirect(reverse('library:authors'))
    else:
        countries = Country.objects.all()
        context = {'countries': countries}
        return render(request, 'library/add_author.html', context)


def add_book(request):
    if request.method == 'POST':
        new_book = Book()
        new_book.title = request.POST['title']
        new_book.publication_date = request.POST['publication_date']
        new_book.author = Author.objects.get(pk=request.POST['author'])
        new_book.language = Language.objects.get(pk=request.POST['language'])
        new_book.save()
        # TODO: redirect to the author page
        return HttpResponseRedirect(reverse('library:authors'))
    else:
        languages = Language.objects.all()
        authors = Author.objects.order_by('last_name')
        context = {
            'languages': languages,
            'authors': authors
        }
        return render(request, 'library/add_book.html', context)


def upload_authors(request):
    if request.method == 'POST':
        author_file = request.FILES['author_file']
        author_data = author_file.read().decode('UTF-8')
        io_string = io.StringIO(author_data)
        reader = csv.DictReader(io_string)
        # TODO: validate the fieldnames
        # TODO: centralize the author creation logic - this is mostly the same as add_author()
        for row in reader:
            new_author = Author()
            new_author.first_name = row['first_name']
            new_author.last_name = row['last_name']
            new_author.birth_date = datetime.strptime(row['birth_date'], YMD_FORMAT).date()
            if row['death_date']:
                new_author.death_date = datetime.strptime(row['death_date'], YMD_FORMAT).date()
            new_author.country, created = Country.objects.get_or_create(country=row['country'])
            new_author.save()
        return HttpResponseRedirect(reverse('library:authors'))
    else:
        return render(request, 'library/author_upload.html')


def upload_books(request):
    if request.method == 'POST':
        book_file = request.FILES['book_file']
        book_data = book_file.read().decode('UTF-8')
        io_string = io.StringIO(book_data)
        reader = csv.DictReader(io_string)
        for row in reader:
            new_book = Book()
            new_book.title = row['title']
            new_book.publication_date = datetime.strptime(row['publication_date'], YMD_FORMAT).date()
            new_book.language, created = Language.objects.get_or_create(language=row['language'])
            new_book.author = Author.objects.get(id=row['author_id'])
            new_book.save()
        return HttpResponseRedirect(reverse('library:authors'))
    else:
        return render(request, 'library/book_upload.html')

library/templates/library/add_author.html
<h1>Create a new Author</h1>

<form action="{% url 'library:add_author' %}" method="post">
{% csrf_token %}
        First name: <input type="text" name="first_name"><br>
        Last name: <input type="text" name="last_name" required><br>
        Birth date: <input type="date" name="birth_date" required><br>
        Death date: <input type="date" name="death_date"><br>
        Country: <select name="country" required>
            {% for country in countries %}
            <option value="{{country.id}}">{{country}}</option>
            {% endfor %}
        </select><br>
    <input type="submit">
</form>

library/templates/library/add_book.html
<h1>Create a new Book</h1>

<form action="{% url 'library:add_book' %}" method="post">
{% csrf_token %}
        Author: <select name="author" required>
            {% for author in authors %}
            <option value="{{author.id}}">{{author.first_name}} {{author.last_name}}</option>
            {% endfor %}
        </select><br>
        Title: <input type="text" name="title" required><br>
        Publication date: <input type="date" name="publication_date" required><br>
        Language: <select name="language" required>
            {% for language in languages %}
            <option value="{{language.id}}">{{language}}</option>
            {% endfor %}
        </select><br>
    <input type="submit">
</form>

library/templates/library/author_books.html
<h1>{{author.first_name}} {{author.last_name}}</h1>
<p>Country: {{author.country}}</p>
<p>Born: {{author.birth_date}}</p>
{% if author.death_date %}
<p>Died: {{author.death_date}}</p>
{% endif %}


{% if books %}
<h2>Works by {{author.first_name}} {{author.last_name}}</h2>
<ul>
    {% for book in books %}
    <li><a href="{% url 'library:book_detail' book.id %}">{{ book.title }}</a> ({{ book.publication_date.year }})</li>
    {% endfor %}
</ul>
{% else %}
<p>No books to display</p>
{% endif %}

<a href="{% url 'library:add_book' %}">Add a book</a>

library/templates/library/author_upload.html
<h1>Upload a CSV of author profiles</h1>
<ul>
    <li>first_name</li>
    <li>last_name</li>
    <li>birth_date</li>
    <li>death_date (optional)</li>
    <li>country</li>
</ul>

<form action="{% url 'library:upload_authors' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" id="author_file" name="author_file">
    <button type="submit">Upload</button>
</form>

library/templates/library/authors.html
<h1>Authors</h1>

{% if author_list %}
<ul>
    {% for author in author_list %}
    <li><a href="{% url 'library:authors_works' author.id %}">{{ author.first_name}} {{author.last_name}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No authors to display</p>
{% endif %}

<a href="{% url 'library:add_author' %}">Add an Author</a><br>
<a href="{% url 'library:upload_authors' %}">Upload CSV of Authors</a>

library/templates/library/book_detail.html
<h1>{{ book.title }}</h1>

<p>Author: {{ book.author.first_name }} {{ book.author.last_name }}</p>
<p>Year: {{ book.publication_date.year }}</p>
<p>Language: {{ book.language }}</p>

library/templates/library/book_upload.html
<h1>Upload a CSV of author profiles</h1>
<ul>
    <li>title</li>
    <li>language</li>
    <li>birth_date</li>
    <li>publication_date</li>
    <li>author_id</li>
</ul>

<form action="{% url 'library:upload_books' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" id="book_file" name="book_file">
    <button type="submit">Upload</button>
</form>

library/templates/library/home.html
<h1>Library home page</h1>

<p><a href="{% url 'library:authors' %}">Authors</a></p>

<p><a href="{% url 'library:languages' %}">Languages</a></p>

library/templates/library/language_books.html
<h1>{{language.language}}</h1>

{% if books %}
<h2>Works in {{language.language}}</h2>
<ul>
    {% for book in books %}
    <li><a href="{% url 'library:book_detail' book.id %}">{{ book.title }}</a> - {{book.author.first_name}} {{book.author.last_name}} - ({{ book.publication_date.year }})</li>
    {% endfor %}
</ul>
{% else %}
<p>No books to display</p>
{% endif %}

<a href="{% url 'library:add_book' %}">Add a book</a>

library/templates/library/languages.html
<h1>Languages</h1>

{% if language_list %}
<ul>
    {% for language in language_list %}
    <li><a href="{% url 'library:language_books' language.id %}">{{ language.language }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No languages to display</p>
{% endif %}